# Percobaan dan latihan

In [1]:
# Cek versi library
import sys
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

print("Python      :", sys.version.split()[0])
print("pandas      :", pd.__version__)
print("numpy       :", np.__version__)
print("matplotlib  :", matplotlib.__version__)

Python      : 3.11.16
pandas      : 3.0.5
numpy       : 2.4.6
matplotlib  : 3.11.1

In [2]:
# Tipe data dasar di Python
nama_mahasiswa = "Huddin"         # string (teks)
npm = 2505060070                 # integer (bilangan bulat)
ipk = 3.73                      # float (bilangan desimal)
aktif_kuliah = True             # boolean (benar/salah)

print(f"Nama       : {nama_mahasiswa} ({type(nama_mahasiswa).__name__})")
print(f"NPM        : {npm} ({type(npm).__name__})")
print(f"IPK        : {ipk} ({type(ipk).__name__})")
print(f"Aktif      : {aktif_kuliah} ({type(aktif_kuliah).__name__})")

Nama       : Huddin (str)
NPM        : 2505060070 (int)
IPK        : 3.73 (float)
Aktif      : True (bool)

In [3]:
daftar_nilai = [85, 90, 78, 92, 88]   # list: kumpulan nilai terurut
print("Daftar nilai:", daftar_nilai)
print("Rata-rata   :", sum(daftar_nilai) / len(daftar_nilai))

mahasiswa = {                          # dictionary: pasangan key-value
    "nama": "Budi",
    "npm": 210411001,
    "jurusan": "Teknologi Informasi",
    "semester": 3
}
print("\nData mahasiswa:")
for key, value in mahasiswa.items():
    print(f"  {key}: {value}")

Daftar nilai: [85, 90, 78, 92, 88]
Rata-rata   : 86.6

Data mahasiswa:
  nama: Budi
  npm: 210411001
  jurusan: Teknologi Informasi
  semester: 3

In [4]:
# Membuat DataFrame dari dictionary
# Studi kasus: data penjualan mingguan sebuah UMKM di beberapa kota

data_penjualan = {
    "kota": ["Magelang", "Yogyakarta", "Semarang", "Solo", "Magelang", "Yogyakarta", "Semarang", "Solo"],
    "minggu": [1, 1, 1, 1, 2, 2, 2, 2],
    "produk": ["Kaos", "Kaos", "Kaos", "Kaos", "Kaos", "Kaos", "Kaos", "Kaos"],
    "unit_terjual": [120, 95, 150, 80, 135, 110, 160, 90],
    "harga_satuan": [75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000]
}

df = pd.DataFrame(data_penjualan)
df

         kota  minggu produk  unit_terjual  harga_satuan
0    Magelang       1   Kaos           120         75000
1  Yogyakarta       1   Kaos            95         75000
2    Semarang       1   Kaos           150         75000
3        Solo       1   Kaos            80         75000
4    Magelang       2   Kaos           135         75000
5  Yogyakarta       2   Kaos           110         75000
6    Semarang       2   Kaos           160         75000
7        Solo       2   Kaos            90         75000

In [5]:
# Melihat 5 baris pertama
df.head()

         kota  minggu produk  unit_terjual  harga_satuan
0    Magelang       1   Kaos           120         75000
1  Yogyakarta       1   Kaos            95         75000
2    Semarang       1   Kaos           150         75000
3        Solo       1   Kaos            80         75000
4    Magelang       2   Kaos           135         75000

In [6]:
# Informasi struktur data: jumlah baris, tipe data tiap kolom, dan memori yang digunakan
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   kota          8 non-null      str
 1   minggu        8 non-null      int64
 2   produk        8 non-null      str
 3   unit_terjual  8 non-null      int64
 4   harga_satuan  8 non-null      int64
dtypes: int64(3), str(2)
memory usage: 452.0 bytes

In [7]:
# Ringkasan statistik deskriptif untuk kolom numerik
df.describe()

         minggu  unit_terjual  harga_satuan
count  8.000000      8.000000           8.0
mean   1.500000    117.500000       75000.0
std    0.534522     29.032002           0.0
min    1.000000     80.000000       75000.0
25%    1.000000     93.750000       75000.0
50%    1.500000    115.000000       75000.0
75%    2.000000    138.750000       75000.0
max    2.000000    160.000000       75000.0

In [9]:
# Menambahkan kolom baru hasil perhitungan: total pendapatan = unit_terjual x harga_satuan
df["total_pendapatan"] = df["unit_terjual"] * df["harga_satuan"]
df

         kota  minggu produk  unit_terjual  harga_satuan  total_pendapatan
0    Magelang       1   Kaos           120         75000           9000000
1  Yogyakarta       1   Kaos            95         75000           7125000
2    Semarang       1   Kaos           150         75000          11250000
3        Solo       1   Kaos            80         75000           6000000
4    Magelang       2   Kaos           135         75000          10125000
5  Yogyakarta       2   Kaos           110         75000           8250000
6    Semarang       2   Kaos           160         75000          12000000
7        Solo       2   Kaos            90         75000           6750000

In [10]:
# Filtering: menampilkan hanya data dari kota Magelang
data_magelang = df[df["kota"] == "Magelang"]
data_magelang

       kota  minggu produk  unit_terjual  harga_satuan  total_pendapatan
0  Magelang       1   Kaos           120         75000           9000000
4  Magelang       2   Kaos           135         75000          10125000

In [11]:
# Filtering dengan lebih dari satu kondisi:
# tampilkan data dengan unit_terjual lebih dari 100 DAN minggu ke-2
data_filter = df[(df["unit_terjual"] > 100) & (df["minggu"] == 2)]
data_filter

         kota  minggu produk  unit_terjual  harga_satuan  total_pendapatan
4    Magelang       2   Kaos           135         75000          10125000
5  Yogyakarta       2   Kaos           110         75000           8250000
6    Semarang       2   Kaos           160         75000          12000000

In [12]:
# Group by: total pendapatan per kota (menjumlahkan data minggu 1 dan minggu 2)
total_per_kota = df.groupby("kota")["total_pendapatan"].sum().sort_values(ascending=False)
print("Total pendapatan per kota (2 minggu):")
total_per_kota

Total pendapatan per kota (2 minggu):

kota
Semarang      23250000
Magelang      19125000
Yogyakarta    15375000
Solo          12750000
Name: total_pendapatan, dtype: int64

# Tugas Praktikum

**Soal 1.** Buatlah sebuah DataFrame baru bernama `df_nilai` yang berisi data nilai 5 mahasiswa (kolom: `nama`, `uts`, `uas`). Tambahkan kolom baru `nilai_akhir` yang dihitung dari `(uts * 0.4) + (uas * 0.6)`.

In [15]:
# Bagian import udah ada di cell paling atas saat menguji versi
# 1. Buat dictionary data nilai 5 mahasiswa
data = {
    "nama": ["Kaky", "Tachikoma", "Mia", "Roti", "Huddin"],
    "uts": [85, 70, 90, 60, 95],
    "uas": [80, 75, 88, 65, 90]
}

# 2. Ubah dictionary menjadi DataFrame pandas
df_nilai = pd.DataFrame(data)

# 3. Tambahkan kolom nilai_akhir sesuai rumus
df_nilai["nilai_akhir"] = (df_nilai["uts"] * 0.4) + (df_nilai["uas"] * 0.6)

# 4. Tampilkan DataFrame
df_nilai

        nama  uts  uas  nilai_akhir
0       Kaky   85   80         82.0
1  Tachikoma   70   75         73.0
2        Mia   90   88         88.8
3       Roti   60   65         63.0
4     Huddin   95   90         92.0

Intinya:
- Aku bikin `data` pakai dictionary
- pd.DataFrame(data) bikin struktur data jadi tabel pandas
- df_nilai["nilai_akhir"] membuat kolom baru, isinya operasi perkalian dari bobot uts dan uas dari soal

**Soal 2.** Dari DataFrame `df_nilai` yang telah dibuat, tampilkan hanya mahasiswa dengan `nilai_akhir` di atas 80.

In [16]:
# Filter mahasiswa dengan nilai_akhir > 80
df_diatas_80 = df_nilai[df_nilai["nilai_akhir"] > 80]

# Tampilkan hasil filter
df_diatas_80

     nama  uts  uas  nilai_akhir
0    Kaky   85   80         82.0
2     Mia   90   88         88.8
4  Huddin   95   90         92.0

Intinya:
- df_nilai["nilai_akhir"] > 80 menghasilkan nilai boolean (True/False)
- Membungkus kondisi tersebut ke dalam df_nilai[...] akan menyaring dan hanya menampilkan baris yang bernilai True (nilai di atas 80).